### PR TITLE
Fix use with Sequoia Chameleon

### PR DESCRIPTION
**Pull request by DemiMarie**
See individual commit messages for details.

Fixes: QubesOS/qubes-issues#9483
Fixes: QubesOS/qubes-issues#9527
Fixes: QubesOS/qubes-issues#9528
Fixes: QubesOS/qubes-issues#9529

### CODE REVIEW

**Comment by marmarek** [comment]
CI fails in several jobs.

And also, please add reference to https://github.com/python/cpython/issues/79174 to the description of the commit vendoring in that class.

**Comment by DemiMarie** [comment]
> CI fails in several jobs.

I’ll sort this out 

> And also, please add reference to [python/cpython#79174](https://github.com/python/cpython/issues/79174) to the description of the commit vendoring in that class.

It’s actually worse: we need to vendor _the entire stream infrastructure_, because the `StreamReader` and `StreamWriter` constructors are not part of the public API.  The only supported options are:

1. Use the low-level asyncio API.
2. Use blocking I/O, perhaps wrapping it in an async interface.
3. Use a third-party library that does (1) or (2).
4. Use a socket-based service (but this breaks backwards compatibility).

**Comment by marmarek** [comment]
> It’s actually worse: we need to vendor _the entire stream infrastructure_, because the `StreamReader` and `StreamWriter` constructors are not part of the public API

Documentation says "It is not recommended to instantiate StreamReader objects directly", which is not the same as unsupported.
Anyway, the constructor signature changed last time 5 years ago. Even if not officially supported, I think it's safe to assume it wont break (or _very_ rarely at least).

**Comment by DemiMarie** [comment]
PipelineRetryFailed

**Comment by DemiMarie** [comment]
CI failure is unrelated: https://github.com/Whonix/qubes-template-whonix is missing a signed tag (so paging @adrelanos).

**Review by marmarek — APPROVED** [review]

**Pull request merged**
