### PR TITLE
Support using existing keys for key generation

### PR DESCRIPTION
**Pull request by DemiMarie**
Tested (somewhat) using gpgsm(1).

### CODE REVIEW

**Comment by marmarek** [comment]
And one more thing: can you add a test that uses this feature?

**Comment by DemiMarie** [comment]
> First of all, if that's only for generating keys, then it should be guarded by `self.allow_keygen`.

That is fine.

> But then, the command isn't documented in gpg agent protocol spec, and it isn't clear to me what possible side effects can be. Do you know where to get more info (besides gpg's source code)?

`gpg-connect-agent 'HELP READKEY' /bye` provides some information.

> And one more thing: can you add a test that uses this feature?

Sure.

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
